version: '3.8'

services:
  # API Spring Boot
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutri_thata_api
    environment:
      # Spring Profiles
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_NAME:-nutri_thata_db}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-validate}
      
      # Flyway Configuration
      SPRING_FLYWAY_ENABLED: ${SPRING_FLYWAY_ENABLED:-true}
      SPRING_FLYWAY_URL: jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_NAME:-nutri_thata_db}
      SPRING_FLYWAY_USER: ${DB_USER:-postgres}
      SPRING_FLYWAY_PASSWORD: ${DB_PASSWORD}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      
      # Email Configuration
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:-587}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:-true}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:-true}
      
      # Server Configuration
      SERVER_PORT: ${SERVER_PORT:-8081}
      
      # File Upload Configuration
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:-10MB}
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:-10MB}
      
      # Logging Configuration
      LOGGING_LEVEL_ROOT: ${LOGGING_LEVEL_ROOT:-INFO}
      LOGGING_LEVEL_BR_RAFAALMEIDA1: ${LOGGING_LEVEL_BR_RAFAALMEIDA1:-DEBUG}
      
      # CORS Configuration
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS:-*}
      
      # Frontend URL (necessário para reset de senha)
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      
      # Brevo API Configuration (para emails)
      BREVO_API_KEY: ${BREVO_API_KEY}
      
    ports:
      - "${API_PORT:-8081}:8081"
    volumes:
      - api_uploads:/app/uploads
      - api_storage:/app/storage
      - api_logs:/app/logs
    networks:
      - nutri_thata_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: nutri_thata_nginx
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - nutri_thata_network
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  api_uploads:
    driver: local
  api_storage:
    driver: local
  api_logs:
    driver: local

networks:
  nutri_thata_network:
    driver: bridge 