version: '3.8'

services:
  # API Spring Boot
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutri_thata_api
    environment:
      # Spring Profiles
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:}
      
      # Database Configuration
      DB_HOST: ${DB_HOST:}
      DB_PORT: ${DB_PORT:}
      DB_NAME: ${DB_NAME:}
      DB_USERNAME: ${DB_USERNAME:}
      DB_PASSWORD: ${DB_PASSWORD:}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET:}
      
      # Frontend URL
      FRONTEND_URL: ${FRONTEND_URL:}
      
    ports:
      - "${API_PORT:8081}:8081"
    volumes:
      - api_uploads:/app/uploads
      - api_storage:/app/storage
      - api_logs:/app/logs
    networks:
      - nutri_thata_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  api_uploads:
    driver: local
  api_storage:
    driver: local
  api_logs:
    driver: local

networks:
  nutri_thata_network:
    driver: bridge 