services:
  # API Spring Boot
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutri_thata_api
    network_mode: host
    environment:
      # Spring Profiles
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      
      # Database Configuration
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      
      # Email Configuration (Brevo)
      SMTP_HOST: ${SMTP_HOST}
      SMTP_API_KEY: ${SMTP_API_KEY}
      BREVO_API_KEY: ${BREVO_API_KEY}
      MAIL_FROM_EMAIL: ${MAIL_FROM_EMAIL}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      
      # CORS Configuration
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      
      # Upload Configuration
      UPLOAD_DIRECTORY: ${UPLOAD_DIRECTORY}
      UPLOAD_MAX_FILE_SIZE: ${UPLOAD_MAX_FILE_SIZE}
      UPLOAD_BASE_URL: ${UPLOAD_BASE_URL}
      
      # Invite Configuration
      INVITE_EXPIRATION_DAYS: ${INVITE_EXPIRATION_DAYS}
      INVITE_BASE_URL: ${INVITE_BASE_URL}
      
      # Frontend URL
      FRONTEND_URL: ${FRONTEND_URL}
      
      # Server Configuration
      SERVER_PORT: ${SERVER_PORT}
      
    tmpfs:
      - /tmp
    volumes:
      - api_uploads:/app/uploads
      - api_storage:/app/storage
      - api_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  api_uploads:
    driver: local
  api_storage:
    driver: local
  api_logs:
    driver: local 