version: '3.8'

services:
  # API Spring Boot
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutri_thata_api
    environment:
      # Spring Profiles
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      
      # Database Configuration
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-nutri_thata_db}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-7200000}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION:-604800000}
      
      # Email Configuration (Brevo)
      SMTP_API_KEY: ${SMTP_API_KEY}
      BREVO_API_KEY: ${BREVO_API_KEY}
      MAIL_FROM_EMAIL: ${MAIL_FROM_EMAIL:-rafaprof312@gmail.com}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-Nutri Thata}
      
      # CORS Configuration
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://localhost:3000,http://localhost:8081}
      
      # Upload Configuration
      UPLOAD_DIRECTORY: ${UPLOAD_DIRECTORY:-/app/storage/uploads}
      UPLOAD_MAX_FILE_SIZE: ${UPLOAD_MAX_FILE_SIZE:-10MB}
      UPLOAD_BASE_URL: ${UPLOAD_BASE_URL:-http://localhost:8081}
      
      # Invite Configuration
      INVITE_EXPIRATION_DAYS: ${INVITE_EXPIRATION_DAYS:-7}
      INVITE_BASE_URL: ${INVITE_BASE_URL:-http://localhost:8081}
      
      # Frontend URL
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      
      # Server Configuration
      SERVER_PORT: ${SERVER_PORT:-8081}
      
    ports:
      - "${API_PORT:-8081}:8081"
    volumes:
      - api_uploads:/app/uploads
      - api_storage:/app/storage
      - api_logs:/app/logs
    networks:
      - nutri_thata_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: nutri_thata_nginx
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - nutri_thata_network
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  api_uploads:
    driver: local
  api_storage:
    driver: local
  api_logs:
    driver: local

networks:
  nutri_thata_network:
    driver: bridge 